services:
    mysql-server:
        image: mysql:latest
        environment:
            MYSQL_USER: xusage_finnplay
            MYSQL_PASSWORD: xusage_finnplay
            MYSQL_ROOT_PASSWORD: xusage_finnplay
            MYSQL_DATABASE: xusage_finnplay
        volumes:
            - ./docker/initdb.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 30

    springboot-registration:
        build: .
        image: springboot-registration:latest
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/xusage_finnplay
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: xusage_finnplay
        depends_on:
            mysql-server:
                condition: service_healthy